
version: "3.7"
services:
  landing_alon:
    image: nginx
    restart: always
    volumes:
      - ./:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend

      - traefik.http.routers.landing_alon.tls.certresolver=myresolver
      - traefik.http.routers.landing_alon.rule=Host(`alon.re`)
#      - traefik.http.routers.landingAlon.rule=Host(`alon.re`) || Host(`www.alon.re`)

    networks:
      - frontend

networks:
  frontend:
    external: true
