
version: "3.7"
services:
  landingAlon:
    image: nginx
    restart: always
    volumes:
      - ./:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.landingalon.tls.certresolver=myresolver
      - traefik.http.routers.landingalon.entrypoints=websecure
      - traefik.http.routers.landingalon.rule=Host(`alon.re`)
#      - traefik.http.routers.landingAlon.rule=Host(`alon.re`) || Host(`www.alon.re`)

    networks:
      - frontend

networks:
  frontend:
    external: true
